// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxznxubfhnxdyvnqbmkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4em54dWJmaG54ZHl2bnFibWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjcyNzksImV4cCI6MjA2MTAwMzI3OX0.G6jgqmAPKsz862J7EYxQB_cmt4J0OTS_9I0gfbSWmIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);